# permissions for end users to view khulnasoftservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftserver-viewer-role
rules:
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftservers/status
  verbs:
  - get
