# permissions for end users to view khulnasoftkubeenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftkubeenforcer-viewer-role
rules:
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftkubeenforcers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftkubeenforcers/status
  verbs:
  - get
