# permissions for end users to view khulnasoftdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftdatabase-viewer-role
rules:
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftdatabases/status
  verbs:
  - get
