# permissions for end users to edit khulnasoftscanners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftscanner-editor-role
rules:
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftscanners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftscanners/status
  verbs:
  - get
