# permissions for end users to edit khulnasoftkubeenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftkubeenforcer-editor-role
rules:
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftkubeenforcers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftkubeenforcers/status
  verbs:
  - get
