# permissions for end users to edit khulnasoftenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftenforcer-editor-role
rules:
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftenforcers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.khulnasoft.com
  resources:
  - khulnasoftenforcers/status
  verbs:
  - get
